import {
  mdiAccountAlertOutline,
  mdiAccountOutline,
  mdiArrowTopRight,
  mdiCheck,
  mdiCheckAll,
  mdiCheckCircleOutline,
  mdiChevronRight,
  mdiClockAlertOutline,
  mdiClockOutline,
  mdiClose,
  mdiFilterCheckOutline,
  mdiFilterVariant,
  mdiInboxOutline,
  mdiInformationOutline,
  mdiLaptop,
  mdiRestore,
  mdiTextBoxMultipleOutline,
  mdiUndo,
} from '@mdi/js'
import { aliases } from 'vuetify/iconsets/mdi-svg'
export const signalIcons = {
  ...aliases,
  'mdi-account-alert-outline': 'svg:' + mdiAccountAlertOutline,
  'mdi-account-outline': 'svg:' + mdiAccountOutline,
  'mdi-arrow-top-right': 'svg:' + mdiArrowTopRight,
  'mdi-check': 'svg:' + mdiCheck,
  'mdi-check-all': 'svg:' + mdiCheckAll,
  'mdi-check-circle-outline': 'svg:' + mdiCheckCircleOutline,
  'mdi-chevron-right': 'svg:' + mdiChevronRight,
  'mdi-clock-alert-outline': 'svg:' + mdiClockAlertOutline,
  'mdi-clock-outline': 'svg:' + mdiClockOutline,
  'mdi-close': 'svg:' + mdiClose,
  'mdi-filter-check-outline': 'svg:' + mdiFilterCheckOutline,
  'mdi-filter-variant': 'svg:' + mdiFilterVariant,
  'mdi-inbox-outline': 'svg:' + mdiInboxOutline,
  'mdi-information-outline': 'svg:' + mdiInformationOutline,
  'mdi-laptop': 'svg:' + mdiLaptop,
  'mdi-restore': 'svg:' + mdiRestore,
  'mdi-text-box-multiple-outline': 'svg:' + mdiTextBoxMultipleOutline,
  'mdi-undo': 'svg:' + mdiUndo,
}
